/* Revue de presse, Ville de Mandeure.
   Données compilées le 18 août 2026, période couverte : du 18 août 2024 au 18 août 2026.
   Chaque URL a été vérifiée individuellement ; les résumés sont rédigés
   originalement, sans reprise du texte des articles sources. */

const CATEGORIES = [
  { id: "municipale", label: "Vie municipale & élections", short: "Municipale", color: "#1d4a86" },
  { id: "travaux", label: "Travaux, urbanisme & environnement", short: "Travaux", color: "#8a5a12" },
  { id: "economie", label: "Économie & emploi", short: "Économie", color: "#1f6b4e" },
  { id: "camping", label: "Camping municipal", short: "Camping", color: "#1a7a7a" },
  { id: "culture", label: "Culture & patrimoine", short: "Culture", color: "#5b3390" },
  { id: "sport", label: "Sport & vie associative", short: "Sport", color: "#8f1e3c" },
  { id: "securite", label: "Sécurité & solidarité", short: "Sécurité", color: "#33312b" },
];

const ARTICLES = [
  // --- Vie municipale & élections ---
  {
    date: "2026-08-27", displayDate: "27 août 2026",
    title: "Incendie de la Mairie de Mandeure : les services municipaux temporairement délocalisés",
    url: "https://www.toutmontbeliard.com/2026/08/27/incendie-de-la-mairie-de-mandeure-les-services-municipaux-temporairement-delocalises/",
    source: "ToutMontbéliard.com",
    summary: "Après l'incendie ayant détruit une partie de la toiture de la mairie, la ville reloge temporairement ses services : les services techniques rejoignent les ateliers municipaux, tandis que l'accueil, l'état civil, l'urbanisme et le CCAS sont regroupés au centre culturel.",
    categories: ["municipale", "securite"],
  },
  {
    date: "2026-03-22", displayDate: "22 mars 2026",
    title: "Élections municipales 2026, 2ème tour : résultats de Mandeure, Stéphane Podgora élu",
    url: "https://www.toutmontbeliard.com/2026/03/22/elections-municipales-2026-2eme-tour-resultats-de-mandeure-stephane-podgora-elu/",
    source: "ToutMontbéliard.com",
    summary: "Stéphane Podgora remporte le second tour des municipales à Mandeure avec 52,70 % des voix, devant Gérard Bouché (36,68 %) et Julien Ceccarelli (10,62 %).",
    categories: ["municipale"],
  },
  {
    date: "2026-03-19", displayDate: "19 mars 2026",
    title: "Élections municipales 2026, 2ème tour : les candidats à Mandeure",
    url: "https://www.toutmontbeliard.com/2026/03/19/elections-municipales-2026-2eme-tour-les-candidats-a-mandeure/",
    source: "ToutMontbéliard.com",
    summary: "Mandeure fait partie des seules communes du Pays de Montbéliard où un second tour est nécessaire ; les trois listes se maintiennent pour le scrutin du 22 mars.",
    categories: ["municipale"],
  },
  {
    date: "2026-03-16", displayDate: "Mars 2026 (après le 1er tour)",
    title: "Municipales 2026 : trois candidats pour dynamiser Mandeure",
    url: "https://www.ici.fr/bourgogne-franche-comte/doubs-25/mandeure/municipales-2026-trois-candidats-pour-dynamiser-mandeure-1133822",
    source: "ICI (ex-France Bleu)",
    summary: "Portrait des trois candidats à l'issue du premier tour et de leurs priorités pour une commune de 4 600 habitants confrontée au manque de médecins et de dynamisme.",
    categories: ["municipale"],
  },
  {
    date: "2026-03-10", displayDate: "10 mars 2026",
    title: "Élections municipales 2026, Mandeure, J. Ceccarelli : liste des candidats",
    url: "https://www.toutmontbeliard.com/2026/03/10/elections-municipales-2026-mandeure-j-ceccarelli-liste-des-candidats/",
    source: "ToutMontbéliard.com",
    summary: "Julien Ceccarelli, enseignant de 37 ans, présente sa liste citoyenne « Mandeure Ensemble 2026 », axée sur la sécurité, le développement économique et la démocratie participative.",
    categories: ["municipale"],
  },
  {
    date: "2026-03-04", displayDate: "4 mars 2026",
    title: "Élections municipales 2026, Mandeure, G. Bouché : réunion publique",
    url: "https://www.toutmontbeliard.com/2026/03/04/elections-municipales-2026-mandeure-g-bouche-reunion-publique/",
    source: "ToutMontbéliard.com",
    summary: "Gérard Bouché annonce une réunion publique de campagne le samedi 7 mars, salle du Majestic, dans le cadre de sa liste « Unis pour Mandeure ».",
    categories: ["municipale"],
  },
  {
    date: "2026-03-01", displayDate: "1er mars 2026",
    title: "Mandeure prend un arrêté de couvre-feu pour les mineurs",
    url: "https://www.toutmontbeliard.com/2026/03/01/mandeure-prend-un-arrete-de-couvre-feu-pour-les-mineurs/",
    source: "ToutMontbéliard.com",
    summary: "Par arrêté municipal du 27 février 2026, la ville de Mandeure interdit aux mineurs de moins de 18 ans de circuler seuls sur son territoire entre 22h et 6h.",
    categories: ["municipale", "securite"],
  },
  {
    date: "2026-02-25", displayDate: "25 février 2026",
    title: "Élections municipales 2026, Mandeure, G. Bouché : liste des candidats",
    url: "https://www.toutmontbeliard.com/2026/02/25/elections-municipales-2026-mandeure-g-bouche-liste-des-candidats/",
    source: "ToutMontbéliard.com",
    summary: "Gérard Bouché, adjoint sortant, dévoile sa liste complète « Unis pour Mandeure » de 27 candidats, avec un programme centré sur la voirie, la santé, la sécurité et le commerce local.",
    categories: ["municipale"],
  },
  {
    date: "2025-12-18", displayDate: "18 décembre 2025",
    title: "Radiations des listes électorales à Mandeure : la Ville apporte des précisions",
    url: "https://www.toutmontbeliard.com/2025/12/18/radiations-des-listes-electorales-a-mandeure-la-ville-apporte-des-precisions/",
    source: "ToutMontbéliard.com",
    summary: "Face à des interrogations d'habitants, la mairie explique que les radiations des listes électorales suivent une procédure nationale encadrée par l'INSEE.",
    categories: ["municipale"],
  },
  {
    date: "2025-12-08", displayDate: "8 décembre 2025",
    title: "Élections municipales 2026, Mandeure : Gérard Bouché candidat",
    url: "https://www.toutmontbeliard.com/2025/12/08/elections-municipales-2026-mandeure-gerard-bouche-candidat/",
    source: "ToutMontbéliard.com",
    summary: "Gérard Bouché, adjoint au maire depuis 2020, annonce officiellement sa candidature aux municipales de mars 2026 avec la liste « Unis pour Mandeure ».",
    categories: ["municipale"],
  },

  // --- Travaux, urbanisme & environnement ---
  {
    date: "2026-05-06", displayDate: "6 mai 2026",
    title: "Information travaux à Mandeure : RD437",
    url: "https://www.toutmontbeliard.com/2026/05/06/information-travaux-a-mandeure-rd437/",
    source: "ToutMontbéliard.com",
    summary: "La RD437 a été totalement fermée à la circulation à Mandeure dans la nuit du 6 au 7 mai 2026 pour des travaux de sécurisation de la traversée de l'agglomération.",
    categories: ["travaux"],
  },

  // --- Économie & emploi ---
  {
    date: "2026-06-18", displayDate: "18 juin 2026",
    title: "Le camping municipal des Grands Ansanges de Mandeure a rouvert ses portes pour la saison estivale 2026",
    url: "https://www.toutmontbeliard.com/2026/06/18/le-camping-municipal-des-grands-ansanges-de-mandeure-a-rouvert-ses-portes-pour-la-saison-estivale-2026/",
    source: "ToutMontbéliard.com",
    summary: "Le camping municipal des Grands Ansanges, seul camping du Pays de Montbéliard, a rouvert le 15 juin 2026 avec ses 96 emplacements en bord de Doubs.",
    categories: ["economie", "camping"],
  },
  {
    date: "2026-05-12", displayDate: "12 mai 2026",
    title: "« Nous avons de belles candidatures » : qui pour reprendre le camping municipal Les Grands Ansanges de Mandeure ?",
    url: "https://www.ici.fr/bourgogne-franche-comte/doubs-25/mandeure/nous-avons-de-belles-candidatures-qui-pour-reprendre-le-camping-municipal-les-grands-ansanges-de-mandeure-7796710",
    source: "ICI (ex-France Bleu)",
    summary: "La mairie a lancé un appel à candidatures pour trouver un nouveau gestionnaire du camping municipal ; le maire indique avoir reçu plusieurs candidatures de qualité.",
    categories: ["economie", "camping"],
  },
  {
    date: "2026-05-01", displayDate: "Mai 2026",
    title: "Peugeot Motocycles redevient français : trois dirigeants ont racheté l'entreprise à Mutares",
    url: "https://www.largus.fr/pros/actualite-automobile/peugeot-motocycles-va-redevenir-francais-trois-de-ses-dirigeants-ont-fait-une-offre-a-mutares-30045870.html",
    source: "L'Argus",
    summary: "Le rachat de Peugeot Motocycles, site historique de Mandeure, par son équipe de direction menée par Laurent Lilti a été finalisé début mai 2026, mettant fin à la propriété du fonds allemand Mutares.",
    categories: ["economie"],
  },
  {
    date: "2026-03-11", displayDate: "11 mars 2026",
    title: "Mandeure : la CGT redoute la fermeture de Peugeot Motocycles",
    url: "https://letrois.info/economie-social/mandeure-la-cgt-redoute-la-fermeture-de-peugeot-motocycles/",
    source: "Le Trois",
    summary: "Le syndicat CGT exprime des inquiétudes sur la viabilité du projet de reprise de Peugeot Motocycles par ses dirigeants, pointant un capital de départ jugé faible.",
    categories: ["economie"],
  },
  {
    date: "2026-03-06", displayDate: "6 mars 2026",
    title: "L'un des futurs actionnaires de Peugeot Motocycles annonce « l'engagement formel de maintenir les activités à Mandeure »",
    url: "https://www.ici.fr/emissions/l-info-d-ici-ici-belfort-montbeliard/l-un-des-futurs-actionnaires-de-peugeot-motocycles-annonce-l-engagement-formel-de-maintenir-les-activites-a-mandeure-7326139",
    source: "ICI (ex-France Bleu)",
    summary: "Laurent Lilti, futur actionnaire majoritaire de Peugeot Motocycles, annonce un engagement formel à maintenir les activités de production sur le site de Mandeure.",
    categories: ["economie"],
  },
  {
    date: "2026-03-05", displayDate: "5 mars 2026",
    title: "Peugeot Motocycles : la direction actuelle propose une offre de reprise à l'allemand Mutares pour le site de Mandeure",
    url: "https://www.ici.fr/bourgogne-franche-comte/doubs-25/mandeure/peugeot-motocycles-la-direction-actuelle-propose-une-offre-de-reprise-a-l-allemand-mutares-pour-le-site-de-mandeure-3230659",
    source: "ICI (ex-France Bleu)",
    summary: "L'équipe dirigeante actuelle de Peugeot Motocycles soumet une offre ferme de rachat à Mutares, sur un site employant environ 245 salariés à Mandeure.",
    categories: ["economie"],
  },
  {
    date: "2026-03-05", displayDate: "5 mars 2026",
    title: "Peugeot Motocycles en passe d'être repris par son équipe de direction",
    url: "https://letrois.info/economie-social/peugeot-motocycles-en-passe-detre-repris-par-son-equipe-de-direction/",
    source: "Le Trois",
    summary: "Mutares annonce avoir reçu une offre ferme de rachat de la part de l'équipe de direction de Peugeot Motocycles, qui avait mené depuis 2023 plusieurs initiatives stratégiques.",
    categories: ["economie"],
  },
  {
    date: "2025-10-16", displayDate: "16 octobre 2025",
    title: "Scooter Peugeot Pulsion EVO 125",
    url: "https://www.lerepairedesmotards.com/actualites/2025/scooter-peugeot-pulsion-evo-125.php",
    source: "Le Repaire des Motards",
    summary: "Présentation du nouveau scooter Peugeot Pulsion EVO 125, fabriqué à Mandeure, arrivé chez les concessionnaires début 2026.",
    categories: ["economie"],
  },
  {
    date: "2025-06-03", displayDate: "3 juin 2025",
    title: "Le Mandeure de l'emploi 2025",
    url: "https://www.toutmontbeliard.com/2025/06/03/le-mandeure-de-lemploi-2025/",
    source: "ToutMontbéliard.com",
    summary: "La 5ᵉ édition du forum de l'emploi organisée par le CCAS de Mandeure a réuni employeurs et structures d'accompagnement, notamment autour de l'hôtellerie-restauration.",
    categories: ["economie"],
  },
  {
    date: "2024-09-05", displayDate: "5 septembre 2024",
    title: "Le Mandeure de l'emploi 2024",
    url: "https://www.toutmontbeliard.com/2024/09/05/le-mandeure-de-lemploi-2024-2/",
    source: "ToutMontbéliard.com",
    summary: "La 4ᵉ édition du forum de l'emploi de Mandeure, organisée par le CCAS, a rassemblé entreprises et organismes d'accompagnement de plusieurs secteurs.",
    categories: ["economie"],
  },

  // --- Culture & patrimoine ---
  {
    date: "2026-07-10", displayDate: "10 juillet 2026",
    title: "Le feu d'artifice du 13 juillet 2026 à Mandeure reporté",
    url: "https://www.toutmontbeliard.com/2026/07/10/le-feu-dartifice-du-13-juillet-2026-a-mandeure-reporte/",
    source: "ToutMontbéliard.com",
    summary: "La municipalité a reporté le feu d'artifice initialement prévu le 13 juillet 2026 en raison de la sécheresse et des risques d'incendie liés à la canicule.",
    categories: ["culture"],
  },
  {
    date: "2026-06-11", displayDate: "11 juin 2026",
    title: "Journées Européennes de l'Archéologie 2026",
    url: "https://www.toutmontbeliard.com/2026/06/11/journees-europeennes-de-larcheologie-2026/",
    source: "ToutMontbéliard.com",
    summary: "Le théâtre antique de Mandeure a accueilli les Journées Européennes de l'Archéologie avec visites guidées, conférences et ateliers, dont une présentation du futur musée de la cité antique.",
    categories: ["culture"],
  },
  {
    date: "2025-05-23", displayDate: "23 mai 2025",
    title: "Animations gratuites, concert celtique : un week-end magique vous attend avec les fêtes de Beltaine !",
    url: "https://www.toutmontbeliard.com/2025/05/23/pub-animations-gratuites-concert-celtique-un-week-end-magique-vous-attend-avec-les-fetes-de-beltaine/",
    source: "ToutMontbéliard.com",
    summary: "Les fêtes de Beltaine se sont tenues au théâtre antique de Mandeure avec village gaulois, artisans, ateliers pour enfants et concert celtique.",
    categories: ["culture"],
  },
  {
    date: "2025-05-20", displayDate: "20 mai 2025",
    title: "Fêtes de Beltaine : festivités celtiques au théâtre de Mandeure ce week-end !",
    url: "https://www.toutmontbeliard.com/2025/05/20/pub-fetes-de-beltaine-festivites-celtiques-au-theatre-de-mandeure-ce-week-end/",
    source: "ToutMontbéliard.com",
    summary: "Annonce de la première édition des fêtes de Beltaine organisée par le Pays de Montbéliard Agglomération au théâtre antique de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2024-09-23", displayDate: "23 septembre 2024",
    title: "Mandeure : bientôt un pavillon de valorisation du théâtre gallo-romain",
    url: "https://letrois.info/culture/mandeure-bientot-un-pavillon-de-valorisation-du-theatre-gallo-romain/",
    source: "Le Trois",
    summary: "La première pierre du futur pavillon d'accueil du théâtre gallo-romain a été posée le 21 septembre 2024 : près de 500 m², 2,7 millions d'euros, livraison prévue à l'été 2026.",
    categories: ["culture", "travaux"],
  },

  // --- Sport & vie associative ---
  {
    date: "2026-05-21", displayDate: "21 mai 2026",
    title: "Une randonnée pour mieux connaitre le théâtre antique de Mandeure",
    url: "https://www.ici.fr/emissions/c-est-positif/une-randonnee-pour-mieux-connaitre-le-theatre-antique-de-mandeure-7570993?at_locale=16",
    source: "ICI (ex-France Bleu)",
    summary: "Portrait du club des Randonneurs de Mandeure, environ 120 membres, qui propose des sorties de tous niveaux autour du théâtre antique.",
    categories: ["sport"],
  },
  {
    date: "2025-11-21", displayDate: "21 novembre 2025",
    title: "Le jeune franc-comtois Maxence Ravier, champion du monde de kickboxing à Milan !",
    url: "https://www.macommune.info/le-franc-comtois-maxence-ravier-champion-du-monde-de-kickboxing/",
    source: "macommune.info",
    summary: "Maxence Ravier, jeune mandubien de 14 ans, est devenu champion du monde de kickboxing (K1) à Milan début novembre 2025.",
    categories: ["sport"],
  },

  // --- Sécurité & solidarité ---
  {
    date: "2026-08-25", displayDate: "25 août 2026",
    title: "Incendie à Mandeure : l'Hôtel de Ville frappé par la foudre",
    url: "https://www.toutmontbeliard.com/2026/08/25/incendie-a-mandeure-lhotel-de-ville-frappe-par-la-foudre/",
    source: "ToutMontbéliard.com",
    summary: "Dans la nuit du 24 au 25 août 2026, la foudre a frappé l'hôtel de ville de Mandeure et provoqué un incendie de toiture ; 41 pompiers ont été mobilisés, un pompier légèrement blessé et environ 200 m² de toiture détruits, entraînant la fermeture de la mairie jusqu'à nouvel ordre.",
    categories: ["securite"],
  },
  {
    date: "2026-06-05", displayDate: "5 juin 2026",
    title: "Accident de parapente à Mandeure : un septuagénaire coincé en contrebas de l'aire de décollage",
    url: "https://www.macommune.info/accident-de-parapente-a-mandeure-un-septuagenaire-coince-en-contrebas-de-laire-de-decollage/",
    source: "macommune.info",
    summary: "Un parapentiste de 70 ans a raté son décollage sur le site de Mandeure et a été secouru par les sapeurs-pompiers du Doubs, blessé au bras et au poignet.",
    categories: ["securite"],
  },
  {
    date: "2026-05-20", displayDate: "20-21 mai 2026",
    title: "25 personnes évacuées pour une fuite de gaz à Mandeure",
    url: "https://www.macommune.info/25-personnes-evacuees-pour-une-fuite-de-gaz-a-mandeure/",
    source: "macommune.info",
    summary: "Une fuite de gaz consécutive à des travaux rue du Pont a entraîné l'évacuation de 17 logements et 25 personnes, le temps de réparer la canalisation.",
    categories: ["securite"],
  },
  {
    date: "2026-04-30", displayDate: "30 avril 2026",
    title: "Plusieurs cambriolages et vols signalés dans le Pays de Montbéliard",
    url: "https://www.macommune.info/plusieurs-cambriolages-et-vols-signales-dans-le-pays-de-montbeliard/",
    source: "macommune.info",
    summary: "Parmi plusieurs cambriolages signalés dans le Pays de Montbéliard, un logement de Mandeure a été visité en l'absence des occupants.",
    categories: ["securite"],
  },
  {
    date: "2026-03-11", displayDate: "11 mars 2026",
    title: "Une voiture fonce dans un arbre à Mandeure : un blessé grave",
    url: "https://www.macommune.info/une-voiture-fonce-dans-un-arbre-a-mandeure-un-blesse-grave/",
    source: "macommune.info",
    summary: "Les pompiers sont intervenus chemin des Pâturages après qu'une voiture a percuté un arbre ; les deux occupants, âgés de 17 ans, ont été transportés à l'hôpital.",
    categories: ["securite"],
  },
  {
    date: "2026-03-03", displayDate: "3 mars 2026",
    title: "« On s'amuse à notre façon » : après des incivilités, un arrêté prive de sortie les mineurs de Mandeure entre 22 h et 6 h",
    url: "https://www.ici.fr/emissions/l-info-d-ici-ici-belfort-montbeliard/on-s-amuse-a-notre-facon-apres-des-incivilites-un-arrete-prive-de-sortie-les-mineurs-de-mandeure-entre-22-h-et-6-h-5899366",
    source: "ICI (ex-France Bleu)",
    summary: "Reportage sur les réactions à Mandeure après l'instauration du couvre-feu des mineurs : habitants et jeunes témoignent de points de vue opposés.",
    categories: ["securite"],
  },
  {
    date: "2026-03-01", displayDate: "1er mars 2026",
    title: "Trois personnes interpellées pour vol de métaux à Mandeure",
    url: "https://www.macommune.info/trois-personnes-interpellees-pour-vol-de-metaux-a-mandeure/",
    source: "macommune.info",
    summary: "Après le signalement d'individus chargeant des métaux dérobés près d'un chantier, les gendarmes ont interpellé un homme majeur et deux mineurs.",
    categories: ["securite"],
  },
  {
    date: "2026-02-11", displayDate: "11-12 février 2026",
    title: "Mandeure : un homme menace de se suicider après des violences sur sa compagne",
    url: "https://www.macommune.info/mandeure-un-homme-menace-de-se-suicider-apres-des-violences-sur-sa-compagne/",
    source: "macommune.info",
    summary: "Après des violences signalées, un homme de 31 ans s'est retranché à son domicile avant d'être interpellé sans incident après l'intervention d'une douzaine de gendarmes.",
    categories: ["securite"],
  },
  {
    date: "2025-04-08", displayDate: "8-9 avril 2025",
    title: "Mandeure : un conducteur de quad gravement blessé",
    url: "https://www.macommune.info/mandeure-un-conducteur-de-quad-gravement-blesse/",
    source: "macommune.info",
    summary: "Un quad a percuté l'arrière d'une voiture rue de Baulieu ; son conducteur de 24 ans a été grièvement blessé, les cinq occupants de la voiture sont indemnes.",
    categories: ["securite"],
  },
  // --- Est Républicain (152 articles, 24 août 2025 – 15 août 2026) ---
  {
    date: "2026-08-15", displayDate: "15 août 2026",
    title: "Ils allument un barbecue à même le sol devant un transformateur électrique",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/08/15/ils-allument-un-barbecue-a-meme-le-sol-devant-un-transformateur-electrique",
    source: "Est Républicain",
    summary: "Les pompiers sont intervenus vendredi après-midi pour un début d'incendie causé par un barbecue allumé à même le sol devant un transformateur électrique.",
    categories: ["securite"],
  },
  {
    date: "2026-08-15", displayDate: "15 août 2026",
    title: "Habitant de Grenoble, il revient chaque été passer ses vacances dans le camping de son fief à Mandeure",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/08/15/habitant-de-grenoble-il-revient-chaque-ete-passer-ses-vacances-dans-le-camping-de-son-fief-a-mandeure",
    source: "Est Républicain",
    summary: "Né à Mandeure de parents et grands-parents ouvriers chez Peugeot, un habitant de Grenoble revient chaque été passer ses vacances au camping municipal.",
    categories: ["culture", "camping"],
  },
  {
    date: "2026-08-11", displayDate: "11 août 2026",
    title: "À Mandeure, le seul camping de l'Agglo mise sur les animations pour attirer un public extérieur",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/08/11/a-mandeure-le-seul-camping-de-l-agglo-mise-sur-les-animations-pour-attirer-un-public-exterieur",
    source: "Est Républicain",
    summary: "Repris récemment par la société Régie Tech, le camping municipal des Grands Ansanges mise sur des animations pour attirer un public extérieur à l'agglomération.",
    categories: ["economie", "camping"],
  },
  {
    date: "2026-08-09", displayDate: "9 août 2026",
    title: "L'unique camping du pays de Montbéliard a trouvé son rythme à Mandeure",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/08/09/l-unique-camping-du-pays-de-montbeliard-a-trouve-son-rythme-a-mandeure",
    source: "Est Républicain",
    summary: "Le camping municipal des Grands Ansanges, seul camping de l'agglomération du Pays de Montbéliard, affiche un bon niveau de fréquentation cet été.",
    categories: ["economie", "camping"],
  },
  {
    date: "2026-08-08", displayDate: "8 août 2026",
    title: "Benjamin et Marie",
    url: "https://www.estrepublicain.fr/societe/2026/08/08/benjamin-et-marie",
    source: "Est Républicain",
    summary: "L'adjoint au maire Nicola Basilico a célébré le mariage de Marie Bertrand et Benjamin, samedi en fin de matinée à la mairie de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-07-23", displayDate: "23 juillet 2026",
    title: "À Mandeure, en guerre contre les dépôts sauvages, un élu se débarrasse de ses végétaux",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/07/23/a-mandeure-en-guerre-contre-les-depots-sauvages-un-elu-se-debarrasse-de-ses-vegetaux",
    source: "Est Républicain",
    summary: "Faute d'accès à la déchèterie fermée pour cause de fortes chaleurs, un conseiller municipal de Mandeure a lui-même évacué ses déchets verts, en pleine lutte contre les dépôts sauvages.",
    categories: ["travaux", "municipale"],
  },
  {
    date: "2026-07-19", displayDate: "19 juillet 2026",
    title: "Noces de diamant pour Viviane et Marcel",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/07/19/noces-de-diamant-pour-viviane-et-marcel",
    source: "Est Républicain",
    summary: "Viviane et Marcel Curty ont fêté leurs noces de diamant le samedi 18 juillet, entourés d'une nombreuse assistance.",
    categories: ["culture"],
  },
  {
    date: "2026-07-13", displayDate: "13 juillet 2026",
    title: "Les véhicules d'avant-guerre bientôt sous les projecteurs avec le rallye Charleston",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/07/13/les-vehicules-d-avant-guerre-bientot-sous-les-projecteurs-avec-le-rallye-charleston",
    source: "Est Républicain",
    summary: "Le rallye Charleston réunira le 26 juillet à Mandeure des véhicules antérieurs à 1945.",
    categories: ["culture"],
  },
  {
    date: "2026-07-11", displayDate: "11 juillet 2026",
    title: "Visé par des tirs de mortiers : « Je subis des représailles parce que j'ouvre ma bouche »",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/07/11/vise-par-des-tirs-de-mortiers-je-subis-des-represailles-parce-que-j-ouvre-ma-bouche",
    source: "Est Républicain",
    summary: "Un habitant de Mandeure, régulièrement visé par des dégradations, dénonce des tirs répétés de mortiers d'artifice qu'il attribue à des représailles après ses plaintes.",
    categories: ["securite"],
  },
  {
    date: "2026-07-10", displayDate: "10 juillet 2026",
    title: "Report du feu d'artifice",
    url: "https://www.estrepublicain.fr/politique/2026/07/10/report-du-feu-d-artifice",
    source: "Est Républicain",
    summary: "En raison de la sécheresse et des épisodes caniculaires, la Ville de Mandeure a annoncé le report de son feu d'artifice.",
    categories: ["municipale", "culture"],
  },
  {
    date: "2026-07-10", displayDate: "10 juillet 2026",
    title: "Après une résidence seniors visée à Seloncourt, des mortiers d'artifice tirés, de nuit, contre une habitation à Mandeure",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/07/10/apres-une-residence-seniors-visee-a-seloncourt-des-mortiers-d-artifice-tires-de-nuit-contre-une-habitation-a-mandeure",
    source: "Est Républicain",
    summary: "Dans la nuit, une habitation a été visée à Mandeure par des tirs de mortiers d'artifice, peu après un fait similaire contre une résidence seniors à Seloncourt.",
    categories: ["securite"],
  },
  {
    date: "2026-07-03", displayDate: "3 juillet 2026",
    title: "L'Orchestre d'Harmonie fête ses 140 ans en mode Pop & Groove",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/07/03/l-orchestre-d-harmonie-fete-ses-140-ans-en-mode-i-pop-amp-groove-i",
    source: "Est Républicain",
    summary: "L'Orchestre d'Harmonie de Beaulieu Mandeure (OHBM) a célébré son 140e anniversaire avec un concert dans un esprit résolument pop et groove.",
    categories: ["culture"],
  },
  {
    date: "2026-06-30", displayDate: "30 juin 2026",
    title: "Un salon pour comprendre le handicap : les élèves mobilisés pour l'inclusion",
    url: "https://www.estrepublicain.fr/education/2026/06/30/un-salon-pour-comprendre-le-handicap-les-eleves-mobilises-pour-l-inclusion",
    source: "Est Républicain",
    summary: "Des élèves de Première Bac Pro SAPAT ont organisé un salon pour sensibiliser leurs camarades au handicap et à l'inclusion.",
    categories: ["culture"],
  },
  {
    date: "2026-06-30", displayDate: "30 juin 2026",
    title: "Le seul camping du Pays de Montbéliard tient son gestionnaire pour l'été, mais après ?",
    url: "https://www.estrepublicain.fr/politique/2026/06/30/le-camping-tient-son-gestionnaire-pour-l-ete-mais-apres",
    source: "Est Républicain",
    summary: "Après avoir confié la gestion du camping à Régie Tech pour la saison, son avenir au-delà de l'été reste flou.",
    categories: ["economie", "camping"],
  },
  {
    date: "2026-06-30", displayDate: "30 juin 2026",
    title: "Finances communales : un diagnostic qui appelle à la vigilance",
    url: "https://www.estrepublicain.fr/politique/2026/06/30/finances-communales-un-diagnostic-qui-appelle-a-la-vigilance",
    source: "Est Républicain",
    summary: "Le conseil municipal de Mandeure a pris connaissance d'un diagnostic financier réalisé par un cabinet spécialisé, appelant à la vigilance sur l'état des finances communales.",
    categories: ["municipale"],
  },
  {
    date: "2026-06-25", displayDate: "25 juin 2026",
    title: "Annulation de la compétition de moto du 28 juin",
    url: "https://www.estrepublicain.fr/societe/2026/06/25/annulation-de-la-competition-de-moto-du-28-juin",
    source: "Est Républicain",
    summary: "Face à un épisode caniculaire exceptionnel et la vigilance rouge décrétée dans le Doubs, la compétition de moto prévue le 28 juin a été annulée.",
    categories: ["sport"],
  },
  {
    date: "2026-06-25", displayDate: "25 juin 2026",
    title: "Spectacle et exposition de fin d'année de l'ASCBM le 4 juillet",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/06/25/spectacle-et-exposition-de-fin-d-annee-de-l-ascbm-le-4-juillet",
    source: "Est Républicain",
    summary: "L'Association socio culturelle de Beaulieu Mandeure organise sa fête de fin d'année, spectacle et exposition, le 4 juillet.",
    categories: ["culture"],
  },
  {
    date: "2026-06-25", displayDate: "25 juin 2026",
    title: "Visite du théâtre d'Epomanduodurum le mercredi 1er juillet : on s'inscrit",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/06/25/visite-du-theatre-d-epomanduodurum-le-mercredi-1-sup-er-sup-juillet-on-s-inscrit",
    source: "Est Républicain",
    summary: "Une visite du théâtre gallo-romain de Mandeure était proposée à la tombée du jour le 1er juillet, sur inscription.",
    categories: ["culture"],
  },
  {
    date: "2026-06-25", displayDate: "25 juin 2026",
    title: "Auguste Martinez (Seloncourt) sème des promesses sur la terre battue de Mandeure",
    url: "https://www.estrepublicain.fr/sport/2026/06/25/auguste-martinez-(seloncourt)-seme-des-promesses-sur-la-terre-battue-de-mandeure",
    source: "Est Républicain",
    summary: "Le jeune joueur Auguste Martinez (TC Seloncourt), 14 ans, a remporté le tournoi de tennis disputé sur la terre battue de Mandeure.",
    categories: ["sport"],
  },
  {
    date: "2026-06-23", displayDate: "23 juin 2026",
    title: "Annulation de la manifestation Jeunesse en fête à cause de la canicule",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/06/23/annulation-de-la-manifestation-jeunesse-en-fete-a-cause-de-la-canicule",
    source: "Est Républicain",
    summary: "Sur recommandation de la sous-préfecture, la manifestation « Jeunesse en fête » a été annulée en raison de l'épisode caniculaire.",
    categories: ["culture"],
  },
  {
    date: "2026-06-21", displayDate: "21 juin 2026",
    title: "Le camping lance sa saison avec l'ambiance du Mondial",
    url: "https://www.estrepublicain.fr/economie/2026/06/21/le-camping-lance-sa-saison-avec-l-ambiance-du-mondial",
    source: "Est Républicain",
    summary: "Le camping municipal des Grands Ansanges a lancé sa nouvelle saison le 15 juin, dans l'ambiance de la Coupe du monde de football.",
    categories: ["economie", "camping"],
  },
  {
    date: "2026-06-20", displayDate: "20 juin 2026",
    title: "Pavillon du théâtre gallo-romain de Mandeure : début de la construction fin 2026",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/06/20/pavillon-du-theatre-gallo-romain-de-mandeure-debut-de-la-construction-fin-2026",
    source: "Est Républicain",
    summary: "La construction d'un pavillon d'accueil de plain-pied au théâtre gallo-romain de Mandeure doit débuter fin 2026, voire début 2027 selon la météo.",
    categories: ["culture", "travaux"],
  },
  {
    date: "2026-06-20", displayDate: "20 juin 2026",
    title: "Animation « Jeunesse en fête » mercredi prochain",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/06/20/animation-jeunesse-en-fete-mercredi-prochain",
    source: "Est Républicain",
    summary: "La Ville de Mandeure, le service culture-jeunesse et la médiathèque organisaient une animation « Jeunesse en fête » le mercredi 24 juin.",
    categories: ["culture"],
  },
  {
    date: "2026-06-17", displayDate: "17 juin 2026",
    title: "Fête de la musique, ce samedi",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/06/17/fete-de-la-musique-ce-samedi",
    source: "Est Républicain",
    summary: "Le parvis du Centre Culturel Jean-d'Ormesson a accueilli la Fête de la musique le samedi 20 juin.",
    categories: ["culture"],
  },
  {
    date: "2026-06-14", displayDate: "14 juin 2026",
    title: "Théâtre antique de Mandeure : l'archéologie livre ses secrets aux plus curieux d'entre nous",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/06/14/theatre-antique-de-mandeure-l-archeologie-livre-ses-secrets-aux-plus-curieux-d-entre-nous",
    source: "Est Républicain",
    summary: "Des visites ont permis au public de découvrir les secrets livrés par les fouilles archéologiques du théâtre antique de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-06-13", displayDate: "13 juin 2026",
    title: "Corentin et Valentine",
    url: "https://www.estrepublicain.fr/societe/2026/06/13/corentin-et-valentine",
    source: "Est Républicain",
    summary: "Corentin Hamaric, 26 ans, vérificateur incendie, et Valentine se sont mariés entourés de leurs familles et amis.",
    categories: ["culture"],
  },
  {
    date: "2026-06-13", displayDate: "13 juin 2026",
    title: "Elle fait parler les os et raconte quand les Gaulois mangeaient leurs chiens et les Romains des huîtres",
    url: "https://www.estrepublicain.fr/societe/2026/06/13/quand-les-gaulois-mangeaient-leurs-chiens-et-les-romains-des-huitres",
    source: "Est Républicain",
    summary: "À l'occasion des Journées européennes de l'archéologie au théâtre antique de Mandeure, une spécialiste a présenté les habitudes alimentaires des Gaulois et des Romains.",
    categories: ["culture"],
  },
  {
    date: "2026-06-13", displayDate: "13 juin 2026",
    title: "Jean-Jacques Chipaux honoré pour 40 ans de bénévolat",
    url: "https://www.estrepublicain.fr/societe/2026/06/13/jean-jacques-chipaux-honore-pour-40-ans-de-benevolat",
    source: "Est Républicain",
    summary: "Jean-Jacques Chipaux a été honoré pour ses 40 années de bénévolat lors du traditionnel repas champêtre de l'association des médaillés du Travail.",
    categories: ["culture"],
  },
  {
    date: "2026-06-12", displayDate: "12 juin 2026",
    title: "Un premier poste chez Peugeot Motocycles à Mandeure pour Thomas Paraire, diplômé l'an dernier",
    url: "https://www.estrepublicain.fr/education/2026/06/12/un-premier-poste-chez-peugeot-motocycles-a-mandeure-pour-thomas-paraire-diplome-l-an-dernier",
    source: "Est Républicain",
    summary: "Thomas Paraire, jeune diplômé, a décroché son premier emploi chez Peugeot Motocycles à Mandeure, faisant le choix de rester dans le Nord Franche-Comté.",
    categories: ["economie"],
  },
  {
    date: "2026-06-09", displayDate: "9 juin 2026",
    title: "Tout savoir sur l'archéologie au théâtre antique",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/06/09/tout-savoir-sur-l-archeologie-au-theatre-antique",
    source: "Est Républicain",
    summary: "À l'occasion des Journées européennes de l'archéologie, le théâtre antique de Mandeure a proposé une présentation des fouilles en cours.",
    categories: ["culture"],
  },
  {
    date: "2026-06-06", displayDate: "6 juin 2026",
    title: "Un parapentiste se retrouve coincé dans un arbre à 50 mètres du sol après un décollage raté à Mandeure",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/06/06/un-parapentiste-de-67-ans-se-retrouve-coince-dans-un-arbre-a-50-metres-du-sol-apres-un-decollage-rate",
    source: "Est Républicain",
    summary: "Un parapentiste de 67 ans s'est retrouvé coincé dans un arbre à 50 mètres du sol après un décollage raté sur l'aire de vol libre de Mandeure.",
    categories: ["securite"],
  },
  {
    date: "2026-05-26", displayDate: "26 mai 2026",
    title: "La Fédération régionale des décorés du travail à l'honneur",
    url: "https://www.estrepublicain.fr/societe/2026/05/26/la-federation-regionale-des-decores-du-travail-a-l-honneur",
    source: "Est Républicain",
    summary: "Une délégation de la Fédération régionale des décorés du travail, conduite par sa présidente Hélène Day, a été mise à l'honneur à Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-05-25", displayDate: "25 mai 2026",
    title: "Un ciné concert d'exception pour les 140 ans de l'OHBM",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/05/25/un-cine-concert-d-exception-pour-les-140-ans-de-l-ohbm",
    source: "Est Républicain",
    summary: "Pour ses 140 ans, l'Orchestre d'Harmonie de Beaulieu Mandeure a proposé un ciné-concert plongeant le public dans un univers musical particulier.",
    categories: ["culture"],
  },
  {
    date: "2026-05-24", displayDate: "24 mai 2026",
    title: "Les Vésuliens ont collectionné les titres à Mandeure",
    url: "https://www.estrepublicain.fr/sport/2026/05/24/les-vesuliens-ont-collectionne-les-titres-a-mandeure",
    source: "Est Républicain",
    summary: "Les pilotes vésuliens, dont Lou Pilard, ont remporté plusieurs titres lors des championnats régionaux de BMX organisés à Mandeure.",
    categories: ["sport"],
  },
  {
    date: "2026-05-23", displayDate: "23 mai 2026",
    title: "Feu de haie : une bande d'adolescents suspectée",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/05/23/feu-de-haie-une-bande-d-adolescents-suspectee",
    source: "Est Républicain",
    summary: "Les pompiers sont intervenus vendredi soir pour un feu de haie à Mandeure ; une bande d'adolescents est suspectée d'en être à l'origine.",
    categories: ["securite"],
  },
  {
    date: "2026-05-22", displayDate: "22 mai 2026",
    title: "Le BMX Besançon présent en nombre à Mandeure au championnat BFC",
    url: "https://www.estrepublicain.fr/sport/2026/05/22/le-bmx-besancon-present-en-nombre-a-mandeure-au-championnat-bfc",
    source: "Est Républicain",
    summary: "Le club de BMX de Besançon s'est déplacé en nombre à Mandeure pour le championnat régional de Bourgogne-Franche-Comté.",
    categories: ["sport"],
  },
  {
    date: "2026-05-21", displayDate: "21 mai 2026",
    title: "Le camping municipal confié à un privé pour la saison estivale",
    url: "https://www.estrepublicain.fr/politique/2026/05/21/le-camping-municipal-confie-a-un-prive-pour-la-saison-estivale",
    source: "Est Républicain",
    summary: "Face à l'urgence d'ouvrir le camping pour la saison 2026, le conseil municipal de Mandeure a voté sa gestion à un opérateur privé.",
    categories: ["economie", "municipale", "camping"],
  },
  {
    date: "2026-05-20", displayDate: "20 mai 2026",
    title: "La boulangerie rue de Beaulieu rouvre sous l'enseigne Maison Cassar",
    url: "https://www.estrepublicain.fr/economie/2026/05/20/la-boulangerie-rue-de-beaulieu-rouvre-sous-l-enseigne-maison-cassar",
    source: "Est Républicain",
    summary: "La boulangerie du 68 rue de Beaulieu à Mandeure a rouvert ses portes sous la nouvelle enseigne Maison Cassar.",
    categories: ["economie"],
  },
  {
    date: "2026-05-20", displayDate: "20 mai 2026",
    title: "Fuite de gaz : une vingtaine d'habitants évacués",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/05/20/fuite-de-gaz-une-vingtaine-d-habitants-evacues",
    source: "Est Républicain",
    summary: "Un engin de chantier a percuté une canalisation de gaz rue du Pont à Mandeure, entraînant l'évacuation d'une vingtaine d'habitants.",
    categories: ["securite"],
  },
  {
    date: "2026-05-13", displayDate: "13 mai 2026",
    title: "Ils construisent une vraie boulangerie gallo-romaine au théâtre antique de Mandeure",
    url: "https://www.estrepublicain.fr/societe/2026/05/13/le-theatre-antique-accueillera-bientot-une-boulangerie-gallo-romaine",
    source: "Est Républicain",
    summary: "Une trentaine de bénévoles se sont retrouvés pour participer à la construction d'une reconstitution de boulangerie gallo-romaine au théâtre antique de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-05-08", displayDate: "8 mai 2026",
    title: "La Croix du Combattant remise à Patrice Girardclos",
    url: "https://www.estrepublicain.fr/defense-guerre-conflit/2026/05/08/la-croix-du-combattant-remise-a-patrice-girardclos",
    source: "Est Républicain",
    summary: "Lors de la cérémonie du 8-Mai à Mandeure, la députée de la 4e circonscription Géraldine Grangier a remis la Croix du Combattant à Patrice Girardclos.",
    categories: ["municipale"],
  },
  {
    date: "2026-05-07", displayDate: "7 mai 2026",
    title: "La montre et le scooter : Lip et Peugeot s'offrent une valse à deux temps",
    url: "https://www.estrepublicain.fr/economie/2026/05/07/la-montre-et-le-scooter-lip-et-peugeot-s-offrent-une-valse-a-deux-temps",
    source: "Est Républicain",
    summary: "Un article retrace le destin croisé de l'horloger Lip de Besançon et du fabricant de scooters Peugeot Motocycles, installé à Mandeure.",
    categories: ["economie"],
  },
  {
    date: "2026-05-04", displayDate: "4 mai 2026",
    title: "Déchèterie mobile : permanence annulée à Mandeure",
    url: "https://www.estrepublicain.fr/societe/2026/05/04/decheterie-mobile-permanence-annulee-a-mandeure",
    source: "Est Républicain",
    summary: "La permanence de la déchèterie mobile prévue le 6 mai à Mandeure a été annulée en raison de travaux.",
    categories: ["travaux"],
  },
  {
    date: "2026-04-27", displayDate: "27 avril 2026",
    title: "Une voiture de L'Est Républicain détruite sur un parking à Mandeure",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/04/27/une-voiture-de-i-l-est-republicain-i-detruite-sur-un-parking-a-mandeure",
    source: "Est Républicain",
    summary: "Une voiture du journal a été détruite sur un parking à Mandeure vendredi soir, en marge d'un spectacle de l'humoriste Booder ; le caractère ciblé de l'acte ne fait pas de doute.",
    categories: ["securite"],
  },
  {
    date: "2026-04-21", displayDate: "21 avril 2026",
    title: "Les Vieux Carbus mandubiens de retour sur les routes pour une nouvelle saison",
    url: "https://www.estrepublicain.fr/societe/2026/04/21/les-vieux-carbus-mandubiens-de-retour-sur-les-routes-pour-une-nouvelle-saison",
    source: "Est Républicain",
    summary: "Le club des Vieux Carbus mandubiens a relancé sa saison de sorties en véhicules anciens le dimanche 12 avril.",
    categories: ["culture"],
  },
  {
    date: "2026-04-20", displayDate: "20 avril 2026",
    title: "Une nacelle dédiée aux personnes handicapées",
    url: "https://www.estrepublicain.fr/insolite/2026/04/20/une-nacelle-dediee-aux-personnes-handicapees",
    source: "Est Républicain",
    summary: "Une nacelle a été mise à disposition à Mandeure pour permettre à des personnes handicapées de vivre un moment de dépaysement.",
    categories: ["culture"],
  },
  {
    date: "2026-04-20", displayDate: "20 avril 2026",
    title: "Booder dans une comédie de cambriolage",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/04/20/booder-dans-une-comedie-de-cambriolage",
    source: "Est Républicain",
    summary: "La comédie « Le casse de l'année » a été jouée à Mandeure avec l'humoriste Booder.",
    categories: ["culture"],
  },
  {
    date: "2026-04-13", displayDate: "13 avril 2026",
    title: "Quel avenir pour le camping des Grands Ansanges ?",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/04/13/quel-avenir-pour-le-camping-des-grands-ansanges",
    source: "Est Républicain",
    summary: "À l'approche de l'été, l'avenir du camping des Grands Ansanges restait incertain malgré la présence de la SAS Camping-Car Park sur le site.",
    categories: ["economie", "camping"],
  },
  {
    date: "2026-04-09", displayDate: "9 avril 2026",
    title: "RD 437, écoles et cimetière : ce qu'il faut retenir du conseil municipal",
    url: "https://www.estrepublicain.fr/politique/2026/04/09/seance-apaisee-et-decisions-administratives-au-conseil-municipal",
    source: "Est Républicain",
    summary: "Le conseil municipal de Mandeure s'est tenu dans une ambiance apaisée, abordant notamment les travaux de la RD 437, les écoles et le cimetière.",
    categories: ["municipale", "travaux"],
  },
  {
    date: "2026-04-09", displayDate: "9 avril 2026",
    title: "Appel à candidatures pour le conseil d'administration du Centre communal d'action sociale",
    url: "https://www.estrepublicain.fr/politique/2026/04/09/appel-a-candidatures-pour-le-conseil-d-administration-du-centre-communal-d-action-sociale",
    source: "Est Républicain",
    summary: "Le Centre communal d'action sociale (CCAS) de Mandeure souhaite élargir son conseil d'administration et lance un appel à candidatures.",
    categories: ["securite", "municipale"],
  },
  {
    date: "2026-04-08", displayDate: "8 avril 2026",
    title: "Les collégiens à la découverte du monde professionnel",
    url: "https://www.estrepublicain.fr/education/2026/04/08/les-collegiens-a-la-decouverte-du-monde-professionnel",
    source: "Est Républicain",
    summary: "Dans le cadre du parcours Avenir, des élèves de cinquième du collège Jean-Paul-Guyot de Mandeure ont participé à une découverte du monde professionnel.",
    categories: ["culture"],
  },
  {
    date: "2026-04-07", displayDate: "7 avril 2026",
    title: "Une moisson de récompenses pour Mélogamme au concours des écoles de musique",
    url: "https://www.estrepublicain.fr/education/2026/04/07/une-moisson-de-recompenses-pour-melogamme-au-concours-des-ecoles-de-musique",
    source: "Est Républicain",
    summary: "Seize élèves de l'école de musique Mélogamme de Mandeure ont récolté de nombreuses récompenses en piano et accordéon au concours régional des écoles de musique.",
    categories: ["culture"],
  },
  {
    date: "2026-03-31", displayDate: "31 mars 2026",
    title: "Immersion professionnelle au Canada pour les élèves de BTS",
    url: "https://www.estrepublicain.fr/education/2026/03/31/immersion-professionnelle-au-canada-pour-les-eleves-de-bts",
    source: "Est Républicain",
    summary: "Des étudiants en BTS Services et prestations des secteurs sanitaire et social (SP3S) de Mandeure ont effectué une immersion professionnelle au Canada en mars.",
    categories: ["culture"],
  },
  {
    date: "2026-03-28", displayDate: "28 mars 2026",
    title: "Stéphane Podgora officiellement installé dans le fauteuil de maire, présente sa nouvelle équipe",
    url: "https://www.estrepublicain.fr/politique/2026/03/28/stephane-podgora-officiellement-installe-dans-le-fauteuil-de-maire-presente-sa-nouvelle-equipe",
    source: "Est Républicain",
    summary: "Stéphane Podgora a été officiellement installé maire de Mandeure avec 23 voix sur 27 et a présenté sa nouvelle équipe municipale.",
    categories: ["municipale"],
  },
  {
    date: "2026-03-27", displayDate: "27 mars 2026",
    title: "A 25 ans, Léa Vauthier lance son entreprise de créations pâtissières à Mandeure",
    url: "https://www.estrepublicain.fr/economie/2026/03/27/a-25-ans-lea-vauthier-lance-son-entreprsie-de-creations-patissieres",
    source: "Est Républicain",
    summary: "Léa Vauthier, 25 ans, a donné vie à son rêve en créant LV Pâtisseries, un laboratoire artisanal installé à Mandeure.",
    categories: ["economie"],
  },
  {
    date: "2026-03-27", displayDate: "27 mars 2026",
    title: "Boules lyonnaises : une saison hivernale dynamique",
    url: "https://www.estrepublicain.fr/societe/2026/03/27/boules-lyonnaises-une-saison-hivernale-dynamique",
    source: "Est Républicain",
    summary: "L'Amicale Boules Beaulieu Mandeure, présidée par Didier Grammont, a connu une saison hivernale dynamique.",
    categories: ["sport"],
  },
  {
    date: "2026-03-26", displayDate: "26 mars 2026",
    title: "Fat Jeff électrifie le blues avec un album entre racines et audace",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/03/26/fat-jeff-electrifie-le-blues-avec-un-album-entre-racines-et-audace",
    source: "Est Républicain",
    summary: "Le musicien mandubien Fat Jeff a sorti un nouvel EP de blues rock, « Heavy Lonesome Blues », enregistré en conditions analogiques.",
    categories: ["culture"],
  },
  {
    date: "2026-03-23", displayDate: "23 mars 2026",
    title: "« Notre premier investissement sera humain », Stéphane Podgora désireux de renouer le dialogue",
    url: "https://www.estrepublicain.fr/elections/2026/03/23/notre-premier-investissement-sera-humain-stephane-podgora-desireux-de-renouer-le-dialogue",
    source: "Est Républicain",
    summary: "Vainqueur avec 53 % des voix au second tour, Stéphane Podgora a annoncé vouloir faire de l'humain sa priorité et renouer le dialogue avec les habitants.",
    categories: ["municipale"],
  },
  {
    date: "2026-03-22", displayDate: "22 mars 2026",
    title: "Mandeure : Stéphane Podgora élu maire avec près de 53 % des voix",
    url: "https://www.estrepublicain.fr/elections/2026/03/22/mandeure-stephane-podgora-elu-maire-avec-pres-de-53-des-voix",
    source: "Est Républicain",
    summary: "Stéphane Podgora a été élu maire de Mandeure avec près de 53 % des voix au second tour des élections municipales.",
    categories: ["municipale"],
  },
  {
    date: "2026-03-21", displayDate: "21 mars 2026",
    title: "Un espace multisensoriel à découvrir à la médiathèque",
    url: "https://www.estrepublicain.fr/education/2026/03/21/un-espace-multisensoriel-a-decouvrir-a-la-mediatheque",
    source: "Est Républicain",
    summary: "Un espace multisensoriel, né d'un partenariat avec l'association Sésame Autisme, a été aménagé à la médiathèque de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-03-20", displayDate: "20 mars 2026",
    title: "Quand les maestros de N'oubliez pas les paroles arrivent en ville",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/03/20/quand-les-maestros-de-i-n-oubliez-pas-les-paroles-i-arrivent-en-ville",
    source: "Est Républicain",
    summary: "Des maestros de l'émission télévisée « N'oubliez pas les paroles » se sont produits à Mandeure pour un concert reprenant Balavoine, Piaf et Goldman.",
    categories: ["culture"],
  },
  {
    date: "2026-03-16", displayDate: "16 mars 2026",
    title: "Le salon des hobbies à découvrir à la fin du mois",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/03/16/le-salon-des-hobbies-a-decouvrir-a-la-fin-du-mois",
    source: "Est Républicain",
    summary: "L'Amicale des décorés du travail Faurecia Peugeot Motocycles organise tous les deux ans une exposition, le salon des hobbies, à Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-03-16", displayDate: "16 mars 2026",
    title: "Quelle star du petit écran, depuis 34 ans, se produit à Mandeure vendredi soir ?",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/03/16/quelle-star-du-petit-ecran-depuis-34-ans-se-produit-a-mandeure-vendredi-soir",
    source: "Est Républicain",
    summary: "Patrick Puydebat, connu pour son rôle dans « Hélène et les garçons », s'est produit sur scène à Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-03-15", displayDate: "15 mars 2026",
    title: "À Mandeure, l'heure est à la rupture",
    url: "https://www.estrepublicain.fr/elections/2026/03/15/a-mandeure-l-heure-est-la-rupture",
    source: "Est Républicain",
    summary: "Stéphane Podgora est arrivé largement en tête du premier tour des municipales à Mandeure, signe d'une volonté de changement chez les électeurs.",
    categories: ["municipale"],
  },
  {
    date: "2026-03-15", displayDate: "15 mars 2026",
    title: "Peugeot Motocycles, un avenir incertain et désormais loin du lion",
    url: "https://www.estrepublicain.fr/economie/2026/03/15/peugeot-motocycles-un-avenir-incertain-et-desormais-loin-du-lion",
    source: "Est Républicain",
    summary: "Un billet revient sur l'avenir incertain de Peugeot Motocycles, l'usine mandubienne aujourd'hui éloignée de la marque au lion.",
    categories: ["economie"],
  },
  {
    date: "2026-03-13", displayDate: "13 mars 2026",
    title: "Rires et émotions avec Le kangourou à bretelles",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/03/13/rires-et-emotions-avec-i-le-kangourou-a-bretelles-i",
    source: "Est Républicain",
    summary: "L'Association culturelle de Beaulieu Mandeure et la compagnie Les Lucioles ont présenté la pièce « Le kangourou à bretelles ».",
    categories: ["culture"],
  },
  {
    date: "2026-03-11", displayDate: "11 mars 2026",
    title: "La voiture percute un arbre à Mandeure : les deux occupants hospitalisés",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/03/11/voiture-contre-un-arbre-a-mandeure-les-deux-occupants-hospitalises",
    source: "Est Républicain",
    summary: "Un automobiliste descendant du belvédère a percuté un arbre à Mandeure ; les deux occupants du véhicule ont été hospitalisés.",
    categories: ["securite"],
  },
  {
    date: "2026-03-10", displayDate: "10 mars 2026",
    title: "Julien Ceccarelli conduit la liste « Mandeure Ensemble 2026 »",
    url: "https://www.estrepublicain.fr/elections/2026/03/10/julien-ceccarelli-conduit-la-liste-mandeure-ensemble-2026",
    source: "Est Républicain",
    summary: "Julien Ceccarelli s'est présenté aux élections municipales de Mandeure en tête de la liste « Mandeure Ensemble 2026 ».",
    categories: ["municipale"],
  },
  {
    date: "2026-03-10", displayDate: "10 mars 2026",
    title: "Plus de clarté à Mandeure avec seulement trois listes dans la course",
    url: "https://www.estrepublicain.fr/elections/2026/03/10/plus-de-clarte-a-mandeure-avec-seulement-trois-listes-dans-la-course",
    source: "Est Républicain",
    summary: "Avec seulement trois listes en lice, contre cinq en 2020, les électeurs mandubiens abordaient un scrutin municipal plus lisible.",
    categories: ["municipale"],
  },
  {
    date: "2026-03-06", displayDate: "6 mars 2026",
    title: "Stéphane Podgora conduit la liste « Engagés et Unis pour Mandeure »",
    url: "https://www.estrepublicain.fr/elections/2026/03/06/stephane-podgora-conduit-la-liste-engages-et-unis-pour-mandeure",
    source: "Est Républicain",
    summary: "Stéphane Podgora, candidat aux élections municipales, a présenté sa liste « Engagés et Unis pour Mandeure ».",
    categories: ["municipale"],
  },
  {
    date: "2026-03-06", displayDate: "6 mars 2026",
    title: "En passe d'être racheté, comment Peugeot Motocycles va redevenir 100 % français",
    url: "https://www.estrepublicain.fr/economie/2026/03/06/en-passe-d-etre-rachete-comment-peugeot-motocycles-va-redevenir-100-francais",
    source: "Est Républicain",
    summary: "Trois ans après en avoir fait l'acquisition, le fonds d'investissement allemand Mutares s'apprêterait à céder Peugeot Motocycles, l'usine mandubienne redevenant ainsi 100 % française.",
    categories: ["economie"],
  },
  {
    date: "2026-03-04", displayDate: "4 mars 2026",
    title: "Concert caritatif exceptionnel : Des chansons plein la tête",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/03/04/concert-caritatif-exceptionnel-des-chansons-plein-la-tete",
    source: "Est Républicain",
    summary: "L'ASCBM a proposé le 22 mars au centre culturel de Mandeure un concert caritatif intitulé « Des chansons plein la tête ».",
    categories: ["culture"],
  },
  {
    date: "2026-02-26", displayDate: "26 février 2026",
    title: "RD 437 : les travaux de sécurité revus à 3 millions d'euros",
    url: "https://www.estrepublicain.fr/politique/2026/02/26/rd-437-les-travaux-de-securite-revus-a-3-millions-d-euros",
    source: "Est Républicain",
    summary: "Réuni pour la dernière fois de la mandature, le conseil municipal de Mandeure a revu à la hausse, à 3 millions d'euros, le coût des travaux de sécurisation de la RD 437.",
    categories: ["travaux", "municipale"],
  },
  {
    date: "2026-02-24", displayDate: "24 février 2026",
    title: "Vendredi, c'est théâtre de boulevard avec l'ASCBM",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/02/24/vendredi-c-est-theatre-de-boulevard-avec-l-ascbm",
    source: "Est Républicain",
    summary: "L'ASCBM a proposé une pièce de théâtre de boulevard sur le thème de l'hyper-communication et de ses pièges.",
    categories: ["culture"],
  },
  {
    date: "2026-02-22", displayDate: "22 février 2026",
    title: "Concours de tarot au centre culturel lundi 9 mars",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/02/22/concours-de-tarot-au-centre-culturel-lundi-9-mars",
    source: "Est Républicain",
    summary: "L'Association socio culturelle de Beaulieu Mandeure a organisé un concours de tarot au centre culturel le lundi 9 mars.",
    categories: ["culture"],
  },
  {
    date: "2026-02-22", displayDate: "22 février 2026",
    title: "Ils dérobent des bijoux chez un couple de personnes âgées",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/02/22/ils-derobent-des-bijoux-chez-un-couple-de-personnes-agees",
    source: "Est Républicain",
    summary: "Trois personnes se sont présentées samedi après-midi au domicile d'un couple de nonagénaires mandubiens pour y dérober des bijoux.",
    categories: ["securite"],
  },
  {
    date: "2026-02-21", displayDate: "21 février 2026",
    title: "Quatre formations sur scène au Festival des chorales",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/02/21/quatre-formations-sur-scene-au-festival-des-chorales",
    source: "Est Républicain",
    summary: "Le chœur de Mandeure Couleurs vocales a organisé le Festival des chorales, réunissant quatre formations sur scène.",
    categories: ["culture"],
  },
  {
    date: "2026-02-20", displayDate: "20 février 2026",
    title: "Inscriptions ouvertes pour une séance d'art-thérapie sur le thème « la peur »",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/02/20/inscriptions-ouvertes-pour-une-seance-d-art-therapie-sur-le-theme-la-peur",
    source: "Est Républicain",
    summary: "Un atelier d'art-thérapie sur le thème de la peur devait se tenir le 7 mars au local de l'ASCBM à Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-02-19", displayDate: "19 février 2026",
    title: "« Le contrat est rempli à 100 % » : Yohann Jeambrun (MC Mandeure) de retour sur la piste après cinq mois d'immobilisation",
    url: "https://www.estrepublicain.fr/sport/2026/02/19/le-contrat-est-rempli-a-100-yohann-jeambrun-(mc-mandeure)-de-retour-sur-la-piste-apres-cinq-mois-d-immobilisation",
    source: "Est Républicain",
    summary: "Le pilote moto Yohann Jeambrun, du MC Mandeure, a repris l'entraînement après cinq mois d'immobilisation suite à une blessure.",
    categories: ["sport"],
  },
  {
    date: "2026-02-18", displayDate: "18 février 2026",
    title: "Ces cris dans la nuit en avance sur la saison",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/02/18/ces-cris-dans-la-nuit-en-avance-sur-la-saison",
    source: "Est Républicain",
    summary: "Des nuisances nocturnes habituellement estivales (cris, tapage, protoxyde d'azote) touchent désormais Mandeure en plein hiver.",
    categories: ["securite"],
  },
  {
    date: "2026-02-13", displayDate: "13 février 2026",
    title: "Mandeure : retranché chez lui, un homme menace de se suicider",
    url: "https://www.estrepublicain.fr/encadres/2026/02/13/mandeure-retranche-chez-lui-un-homme-menace-se-suicider",
    source: "Est Républicain",
    summary: "Un homme retranché chez lui à Mandeure a menacé de mettre fin à ses jours ; le maire Jean-Pierre Hocquet a confirmé les faits, survenus un mercredi.",
    categories: ["securite"],
  },
  {
    date: "2026-02-10", displayDate: "10 février 2026",
    title: "Le club des Vieux Carbus en route pour une nouvelle saison",
    url: "https://www.estrepublicain.fr/societe/2026/02/10/le-club-des-vieux-carbus-en-route-pour-une-nouvelle-saison",
    source: "Est Républicain",
    summary: "Lors de son assemblée générale, le club de véhicules anciens Vieux Carbus Mandubiens, présidé par Laurent Grandgirard, a dressé son bilan et préparé la saison à venir.",
    categories: ["culture"],
  },
  {
    date: "2026-02-06", displayDate: "6 février 2026",
    title: "Orientations budgétaires au menu de l'avant-dernier conseil municipal",
    url: "https://www.estrepublicain.fr/politique/2026/02/06/orientations-budgetaires-au-menu-de-l-avant-dernier-conseil-municipal",
    source: "Est Républicain",
    summary: "Réunis pour l'avant-dernier conseil municipal du mandat, les élus de Mandeure ont validé à l'unanimité les orientations budgétaires de la commune.",
    categories: ["municipale"],
  },
  {
    date: "2026-02-04", displayDate: "4 février 2026",
    title: "Stéphane Podgora candidat pour la deuxième fois",
    url: "https://www.estrepublicain.fr/elections/2026/02/04/stephane-podgora-candidat-pour-la-deuxieme-fois",
    source: "Est Républicain",
    summary: "Stéphane Podgora se présente une nouvelle fois aux élections municipales à Mandeure, avec l'ambition de redonner de l'élan et de la participation citoyenne à la ville.",
    categories: ["municipale"],
  },
  {
    date: "2026-01-31", displayDate: "31 janvier 2026",
    title: "Les inscriptions pour la soirée dansante de l'ASCBM sont ouvertes",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/01/31/les-inscriptions-pour-la-soiree-dansante-de-l-ascbm-sont-ouvertes",
    source: "Est Républicain",
    summary: "L'Association socio-culturelle de Beaulieu Mandeure organise une soirée dansante le 21 février 2026, dont les inscriptions viennent d'ouvrir.",
    categories: ["culture"],
  },
  {
    date: "2026-01-26", displayDate: "26 janvier 2026",
    title: "Préparatrice en pharmacie et voleuse compulsive : 6 mois avec sursis",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2026/01/26/preparatrice-en-pharmacie-et-voleuse-compulsive-6-mois-avec-sursis",
    source: "Est Républicain",
    summary: "Une quinquagénaire a été condamnée à six mois de prison avec sursis pour s'être introduite en mai 2023 dans la pharmacie de Mandeure où elle avait travaillé, afin d'y dérober des produits.",
    categories: ["securite"],
  },
  {
    date: "2026-01-26", displayDate: "26 janvier 2026",
    title: "Les Manlieux Classe 75 organisent un vide-greniers",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/01/26/les-manlieux-classe-75-organisent-un-vide-greniers",
    source: "Est Républicain",
    summary: "L'association Les Manlieux Classe 75 a organisé un vide-greniers à Mandeure le 1er février.",
    categories: ["culture"],
  },
  {
    date: "2026-01-24", displayDate: "24 janvier 2026",
    title: "Une comédie autour d'un SMS mal interprété",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/01/24/une-comedie-autour-d-un-sms-mal-interprete",
    source: "Est Républicain",
    summary: "La troupe de Fabienne Galloux et Charles Meurisse joue « Muchas Gracias », une comédie de boulevard présentée à Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-01-17", displayDate: "17 janvier 2026",
    title: "Municipales : Julien Ceccarelli candidat pour la deuxième fois",
    url: "https://www.estrepublicain.fr/elections/2026/01/17/municipales-julien-ceccarelli-candidat-pour-la-deuxieme-fois",
    source: "Est Républicain",
    summary: "Entré en politique en 2012, Julien Ceccarelli se représente pour la deuxième fois aux élections municipales de Mandeure.",
    categories: ["municipale"],
  },
  {
    date: "2026-01-16", displayDate: "16 janvier 2026",
    title: "À Mandeure, tout est long dans le pavillon",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/01/16/a-mandeure-tout-est-long-dans-le-pavillon",
    source: "Est Républicain",
    summary: "Ce billet revient avec ironie sur les retards accumulés dans la construction du pavillon de valorisation du site antique de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-01-16", displayDate: "16 janvier 2026",
    title: "Les travaux du pavillon de valorisation du site antique vont enfin commencer",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/01/16/les-travaux-du-pavillon-de-valorisation-du-site-antique-vont-enfin-commencer",
    source: "Est Républicain",
    summary: "Après plusieurs décennies de discussions et une première pierre posée dès l'automne 2024, les travaux du pavillon de valorisation du site antique de Mandeure démarrent enfin.",
    categories: ["culture", "travaux"],
  },
  {
    date: "2026-01-14", displayDate: "14 janvier 2026",
    title: "Municipales 2026 : Gérard Bouché candidat à la mairie",
    url: "https://www.estrepublicain.fr/elections/2026/01/14/municipales-2026-gerard-bouche-candidat-a-la-mairie",
    source: "Est Républicain",
    summary: "Adjoint aux travaux de Jean-Pierre Hocquet, Gérard Bouché annonce sa candidature à la mairie de Mandeure dans la continuité de l'équipe sortante.",
    categories: ["municipale"],
  },
  {
    date: "2026-01-13", displayDate: "13 janvier 2026",
    title: "Concert du Nouvel An : les grands classiques de l'opéra à l'auditorium",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/01/13/concert-du-nouvel-an-les-grands-classiques-de-l-opera-a-l-auditorium",
    source: "Est Républicain",
    summary: "Après un concert d'hiver ayant réuni plus de 800 spectateurs, l'Orchestre d'harmonie de Beaulieu Mandeure propose un concert du Nouvel An consacré aux grands classiques de l'opéra.",
    categories: ["culture"],
  },
  {
    date: "2026-01-11", displayDate: "11 janvier 2026",
    title: "La trentième bourse de miniatures le 18 janvier",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/01/11/la-trentieme-bourse-de-miniatures-le-18-janvier",
    source: "Est Républicain",
    summary: "Le club du modèle réduit organise la 30e édition de sa bourse de miniatures à Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2026-01-09", displayDate: "9 janvier 2026",
    title: "La Maison familiale et rurale célèbre ses diplômés",
    url: "https://www.estrepublicain.fr/education/2026/01/09/la-maison-familiale-et-rurale-celebre-ses-diplomes",
    source: "Est Républicain",
    summary: "La Maison familiale et rurale (MFR) du Pays de Montbéliard, basée à Mandeure, a organisé une cérémonie de remise des diplômes à ses élèves.",
    categories: ["culture"],
  },
  {
    date: "2026-01-07", displayDate: "7 janvier 2026",
    title: "A Mandeure, la ferme Maitre prend la suite de l'institution Brand dans la production d'œufs",
    url: "https://www.estrepublicain.fr/economie/2026/01/07/a-mandeure-la-ferme-maitre-prend-la-suite-de-l-institution-brand-dans-la-production-d-oeufs",
    source: "Est Républicain",
    summary: "À Mandeure, la ferme Maitre reprend l'activité de production d'œufs de l'historique ferme Brand, connue pour ses distributeurs automatiques.",
    categories: ["economie"],
  },
  {
    date: "2026-01-05", displayDate: "5 janvier 2026",
    title: "Direction Ibiza avec le théâtre de boulevard : « Muchas Gracias », entre rires et quiproquos",
    url: "https://www.estrepublicain.fr/culture-loisirs/2026/01/05/direction-ibiza-avec-le-theatre-de-boulevard-i-muchas-gracias-i-entre-rires-et-quiproquos",
    source: "Est Républicain",
    summary: "Le centre culturel mandubien accueille en fin de mois la comédie « Muchas Gracias », portée par un habitué des planches locales.",
    categories: ["culture"],
  },
  {
    date: "2025-12-17", displayDate: "17 décembre 2025",
    title: "Dépôts sauvages : la municipalité de Mandeure va taper au portefeuille à partir de 2026",
    url: "https://www.estrepublicain.fr/environnement/2025/12/17/depots-sauvages-la-municipalite-va-taper-au-portefeuille",
    source: "Est Républicain",
    summary: "Face à la hausse des dépôts sauvages en zone urbaine et en forêt, la Ville de Mandeure a décidé de sanctionner financièrement les auteurs d'incivilités à partir de 2026.",
    categories: ["travaux"],
  },
  {
    date: "2025-12-16", displayDate: "16 décembre 2025",
    title: "Fin 2028, des logements et un pôle de santé à la place de l'ancien temple",
    url: "https://www.estrepublicain.fr/sante/2025/12/16/fin-2028-des-logements-et-un-pole-de-sante-a-la-place-de-l-ancien-temple",
    source: "Est Républicain",
    summary: "Le promoteur Nexity va construire vingt-et-un logements et un pôle de santé à Mandeure, entre le stade municipal et le site de l'ancien temple, avec une livraison prévue fin 2028.",
    categories: ["travaux"],
  },
  {
    date: "2025-12-14", displayDate: "14 décembre 2025",
    title: "Avec son 103 nouvelle génération, Peugeot Motocycles veut toujours croire en son étoile",
    url: "https://www.estrepublicain.fr/economie/2025/12/14/avec-son-103-nouvelle-generation-peugeot-motocycles-veut-toujours-croire-en-son-etoile",
    source: "Est Républicain",
    summary: "Plus d'un demi-siècle après le lancement du cyclomoteur mythique vendu à plus de trois millions d'exemplaires, Peugeot Motocycles à Mandeure mise sur une nouvelle génération du 103.",
    categories: ["economie"],
  },
  {
    date: "2025-12-14", displayDate: "14 décembre 2025",
    title: "Peugeot Motocycles : habiller la mariée pour mieux s'en défaire ?",
    url: "https://www.estrepublicain.fr/economie/2025/12/14/peugeot-motocycles-habiller-la-mariee-pour-mieux-s-en-defaire",
    source: "Est Républicain",
    summary: "Cet article s'interroge sur la stratégie du groupe Mutares concernant l'avenir de Peugeot Motocycles Mandeure-Valentigney (PMTC).",
    categories: ["economie"],
  },
  {
    date: "2025-12-13", displayDate: "13 décembre 2025",
    title: "Chez Peugeot Motocycles, le 103, un numéro d'illusionniste ?",
    url: "https://www.estrepublicain.fr/economie/2025/12/13/chez-peugeot-motocycles-le-103-un-numero-d-illusionniste",
    source: "Est Républicain",
    summary: "Ce billet revient sur le mythe entourant le lancement du nouveau cyclomoteur 103 chez Peugeot Motocycles à Mandeure.",
    categories: ["economie"],
  },
  {
    date: "2025-12-13", displayDate: "13 décembre 2025",
    title: "Record atteint pour le Manduthon avec 12 350 € récoltés au profit de l'AFM Téléthon",
    url: "https://www.estrepublicain.fr/societe/2025/12/13/record-atteint-pour-le-manduthon-avec-12-350-recoltes-au-profit-de-l-afm-telethon",
    source: "Est Républicain",
    summary: "L'association Manduthon a battu son record lors de l'édition 2025 du Téléthon à Mandeure, en récoltant 12 350 euros au profit de l'AFM.",
    categories: ["securite"],
  },
  {
    date: "2025-12-13", displayDate: "13 décembre 2025",
    title: "Bilan positif et résultats encourageants pour le club de boules",
    url: "https://www.estrepublicain.fr/societe/2025/12/13/bilan-positif-et-resultats-encourageants-pour-le-club-de-petanque",
    source: "Est Républicain",
    summary: "L'Amicale boules de Beaulieu Mandeure (ABBM) a tenu son assemblée générale annuelle en présence du maire, dressant un bilan sportif positif.",
    categories: ["sport"],
  },
  {
    date: "2025-12-12", displayDate: "12 décembre 2025",
    title: "Musique : une occasion idéale de s'émerveiller ce week-end",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/12/12/musique-une-occasion-ideale-de-s-emerveiller-ce-week-end",
    source: "Est Républicain",
    summary: "L'Orchestre d'harmonie de Beaulieu Mandeure propose une expérience musicale au public de la ville le week-end.",
    categories: ["culture"],
  },
  {
    date: "2025-12-07", displayDate: "7 décembre 2025",
    title: "Collecte solidaire avec la Croix rouge : participer en offrant une boîte de Noël",
    url: "https://www.estrepublicain.fr/politique/2025/12/07/collecte-solidaire-avec-la-croix-rouge-participer-en-offrant-une-boite-de-noel",
    source: "Est Républicain",
    summary: "Le CCAS de Mandeure, en partenariat avec la Croix Rouge de Montbéliard, organise une collecte de boîtes de Noël solidaires.",
    categories: ["securite"],
  },
  {
    date: "2025-12-06", displayDate: "6 décembre 2025",
    title: "La collecte pour la Ligue contre le cancer a rapporté plus de 10 000 euros",
    url: "https://www.estrepublicain.fr/sante/2025/12/06/la-collecte-pour-la-ligue-contre-le-cancer-a-rapporte-plus-de-10-000-euros",
    source: "Est Républicain",
    summary: "Grâce à la générosité des Mandubiens, 10 073 euros ont été collectés cette année au profit de la Ligue contre le cancer.",
    categories: ["securite"],
  },
  {
    date: "2025-12-05", displayDate: "5 décembre 2025",
    title: "Assemblée générale du Moto club : un nouveau comité élu",
    url: "https://www.estrepublicain.fr/societe/2025/12/05/assemblee-generale-du-moto-club-un-nouveau-comite-elu",
    source: "Est Républicain",
    summary: "Réunis en nombre, les membres du Moto club de Mandeure ont assisté à leur assemblée générale, qui a débouché sur l'élection d'un nouveau comité.",
    categories: ["sport"],
  },
  {
    date: "2025-12-05", displayDate: "5 décembre 2025",
    title: "Un nouvel élan pour préserver la mémoire de la Résistance",
    url: "https://www.estrepublicain.fr/societe/2025/12/05/un-nouvel-elan-pour-preserver-la-memoire-de-la-resistance",
    source: "Est Républicain",
    summary: "Une nouvelle association, la MHRPM, s'est constituée à Mandeure pour fédérer les initiatives dédiées à la mémoire de la Résistance dans le Pays de Montbéliard.",
    categories: ["culture"],
  },
  {
    date: "2025-12-05", displayDate: "5 décembre 2025",
    title: "Vol de métaux chez Das Solar : deux hommes écopent d'un an de prison",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2025/12/05/vol-de-metaux-chez-das-solar-deux-hommes-ecopent-d-un-an-de-prison",
    source: "Est Républicain",
    summary: "Après une première vague d'interpellations, deux hommes de 23 et 25 ans ont été condamnés à un an de prison pour des vols de métaux commis chez Das Solar à Mandeure.",
    categories: ["securite"],
  },
  {
    date: "2025-11-29", displayDate: "29 novembre 2025",
    title: "Séance de sensibilisation aux médias et aux réseaux sociaux pour des élèves de la Maison familiale et rurale",
    url: "https://www.estrepublicain.fr/education/2025/11/29/seance-de-sensibilisation-aux-medias-et-aux-reseaux-sociaux-pour-des-eleves-de-la-maison-familiale-et-rurale",
    source: "Est Républicain",
    summary: "Une classe de 4e de la Maison familiale et rurale de Mandeure a participé à une séance interactive de sensibilisation aux médias et aux réseaux sociaux.",
    categories: ["culture"],
  },
  {
    date: "2025-11-27", displayDate: "27 novembre 2025",
    title: "Huit ateliers pour découvrir internet : 10 seniors formés au numérique",
    url: "https://www.estrepublicain.fr/politique/2025/11/27/huit-ateliers-pour-decouvrir-internet-10-seniors-formes-au-numerique",
    source: "Est Républicain",
    summary: "Grâce à un partenariat entre le CCAS de Mandeure et Saint-Vit Informatique, dix seniors ont suivi huit ateliers pour se former au numérique.",
    categories: ["securite"],
  },
  {
    date: "2025-11-25", displayDate: "25 novembre 2025",
    title: "La Sainte-Cécile célébrée par l'harmonie : distinctions et convivialité à l'honneur",
    url: "https://www.estrepublicain.fr/societe/2025/11/25/la-sainte-cecile-celebree-par-l-harmonie-distinctions-et-convivialite-a-l-honneur",
    source: "Est Républicain",
    summary: "À l'occasion de la Sainte-Cécile, l'Orchestre d'harmonie de Beaulieu Mandeure a récompensé plusieurs de ses membres lors d'une soirée conviviale.",
    categories: ["culture"],
  },
  {
    date: "2025-11-24", displayDate: "24 novembre 2025",
    title: "Pilote depuis dix ans, Yohann Jeambrun présente sa Yamaha R1 à la fête du Beaujolais nouveau",
    url: "https://www.estrepublicain.fr/societe/2025/11/24/pilote-depuis-dix-ans-yohann-jeambrun-presente-sa-yamaha-r1-a-la-fete-du-beaujolais-nouveau",
    source: "Est Républicain",
    summary: "Organisée par l'association JMX Team, la fête du Beaujolais nouveau à Mandeure a été l'occasion pour le motard Yohann Jeambrun de présenter sa Yamaha R1.",
    categories: ["sport", "culture"],
  },
  {
    date: "2025-11-14", displayDate: "14 novembre 2025",
    title: "Téléthon : récolter plus que les 10 480 euros de 2024",
    url: "https://www.estrepublicain.fr/societe/2025/11/14/telethon-recolter-plus-que-les-10-480-euros-de-2024",
    source: "Est Républicain",
    summary: "Le Manduthon prépare son week-end solidaire des 6 et 7 décembre au profit du Téléthon, avec l'objectif de dépasser la collecte de 2024.",
    categories: ["securite"],
  },
  {
    date: "2025-11-13", displayDate: "13 novembre 2025",
    title: "Une comédie de boulevard pétillante ce vendredi soir",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/11/13/une-comedie-de-boulevard-petillante-ce-vendredi-soir",
    source: "Est Républicain",
    summary: "Le centre culturel Jean-d'Ormesson de Mandeure accueille une pièce de théâtre de boulevard un vendredi soir.",
    categories: ["culture"],
  },
  {
    date: "2025-11-12", displayDate: "12 novembre 2025",
    title: "Patrice Girardclos honoré par l'Union nationale des combattants",
    url: "https://www.estrepublicain.fr/defense-guerre-conflit/2025/11/12/patrice-girardclos-honore-par-l-union-nationale-des-combattants",
    source: "Est Républicain",
    summary: "Lors de la cérémonie du 11-Novembre à Mandeure, Thierry Bocca, président de l'Union nationale des combattants, a honoré Patrice Girardclos.",
    categories: ["culture"],
  },
  {
    date: "2025-11-12", displayDate: "12 novembre 2025",
    title: "Municipales : à Mandeure, PS et Marcheurs main dans la main",
    url: "https://www.estrepublicain.fr/elections/2025/11/12/municipales-a-mandeure-ps-et-marcheurs-main-dans-la-main",
    source: "Est Républicain",
    summary: "À l'approche des municipales, ce billet évoque un rapprochement pragmatique entre le PS et les Marcheurs à Mandeure.",
    categories: ["municipale"],
  },
  {
    date: "2025-11-11", displayDate: "11 novembre 2025",
    title: "Un salon de l'artisanat et du goût qui séduit le public",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/11/11/un-salon-de-l-artisanat-et-du-gout-qui-seduit-le-public",
    source: "Est Républicain",
    summary: "Le salon de l'artisanat et du goût, organisé par l'Association socioculturelle de Beaulieu Mandeure, a attiré un large public.",
    categories: ["culture", "economie"],
  },
  {
    date: "2025-11-08", displayDate: "8 novembre 2025",
    title: "Brocante des médaillés du travail Faurecia et Peugeot Motocycles le dimanche 16 novembre",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/11/08/brocante-des-medailles-du-travail-faurecia-et-peugeot-motocycles-le-dimanche-16-novembre",
    source: "Est Républicain",
    summary: "Les médaillés du travail de Faurecia et de Peugeot Motocycles Mandeure-Valentigney organisent leur grande brocante annuelle.",
    categories: ["economie"],
  },
  {
    date: "2025-11-07", displayDate: "7 novembre 2025",
    title: "Théâtre : Partenaires particuliers au centre Jean d'Ormesson",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/11/07/theatre-i-partenaires-particuliers-i-au-centre-jean-d-ormesson",
    source: "Est Républicain",
    summary: "La saison théâtrale de l'ASCBM, débutée fin octobre, se poursuit avec la pièce « Partenaires particuliers » au centre culturel Jean d'Ormesson de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2025-11-07", displayDate: "7 novembre 2025",
    title: "Cinq jeunes pianistes font sensation sur la scène nationale",
    url: "https://www.estrepublicain.fr/societe/2025/11/07/cinq-jeunes-pianistes-font-sensation-sur-la-scene-nationale",
    source: "Est Républicain",
    summary: "Cinq jeunes pianistes de l'école Mélogamme de Mandeure se sont illustrés lors de finales nationales.",
    categories: ["culture"],
  },
  {
    date: "2025-11-05", displayDate: "5 novembre 2025",
    title: "Traversée de la commune : un projet de sécurisation à près de 3 millions d'euros",
    url: "https://www.estrepublicain.fr/politique/2025/11/05/traversee-de-la-commune-un-projet-de-securisation-a-pres-de-3-millions-d-euros",
    source: "Est Républicain",
    summary: "Le conseil municipal de Mandeure a validé un vaste plan de sécurisation de la traversée de la commune, réparti sur plusieurs années et représentant près de 3 millions d'euros.",
    categories: ["travaux", "municipale"],
  },
  {
    date: "2025-11-05", displayDate: "5 novembre 2025",
    title: "Un salarié de Peugeot Motocycles victime d'un accident lors d'un essai de moto",
    url: "https://www.estrepublicain.fr/faits-divers-justice/2025/11/05/un-salarie-de-peugeot-motocycles-victime-d-un-accident-lors-d-un-essai-de-moto",
    source: "Est Républicain",
    summary: "Un employé de Peugeot Motocycles a été victime d'une collision avec un utilitaire à une centaine de mètres de l'usine, lors d'un essai de moto.",
    categories: ["securite"],
  },
  {
    date: "2025-11-03", displayDate: "3 novembre 2025",
    title: "Loto organisé par la Confrérie des compagnons du Boitchu",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/11/03/loto-organise-par-la-confrerie-des-compagnons-du-boitchu-gpso",
    source: "Est Républicain",
    summary: "La Confrérie des compagnons du Boitchu a organisé un loto à Mandeure le dimanche 2 novembre.",
    categories: ["culture"],
  },
  {
    date: "2025-11-01", displayDate: "1 novembre 2025",
    title: "Salon de l'artisanat et du goût au centre culturel",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/11/01/salon-de-l-artisanat-et-du-gout-au-centre-culturel",
    source: "Est Républicain",
    summary: "L'ASCBM organise son salon de l'artisanat et du goût au centre culturel de Mandeure.",
    categories: ["culture", "economie"],
  },
  {
    date: "2025-10-30", displayDate: "30 octobre 2025",
    title: "Brocante d'automne organisée par l'ASV Foot Vétérans Valentigney",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/10/30/brocante-d-automne-organisee-par-l-asv-foot-veterans-valentigney-gpso",
    source: "Est Républicain",
    summary: "L'ASV Foot Vétérans Valentigney a organisé une brocante d'automne dans une salle à Mandeure le dimanche 26 octobre.",
    categories: ["culture"],
  },
  {
    date: "2025-10-29", displayDate: "29 octobre 2025",
    title: "Le deuxième week-end de novembre sous le signe de l'artisanat et du goût au centre culturel",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/10/29/le-deuxieme-week-end-de-novembre-sous-le-signe-de-l-artisanat-et-du-gout-au-centre-culturel",
    source: "Est Républicain",
    summary: "L'Association socioculturelle de Beaulieu Mandeure annonce son salon de l'artisanat et du goût pour le deuxième week-end de novembre, au centre culturel de la ville.",
    categories: ["culture", "economie"],
  },
  {
    date: "2025-10-29", displayDate: "29 octobre 2025",
    title: "Chez Peugeot Motocycles, le successeur du mythique 103 sera-t-il lancé en 2026 ?",
    url: "https://www.estrepublicain.fr/economie/2025/10/29/chez-peugeot-motocycles-le-successeur-du-mythique-103-sera-t-il-lance-en-2026",
    source: "Est Républicain",
    summary: "Le directeur général adjoint de Peugeot Motocycles à Mandeure évoque l'éventuel lancement en 2026 d'un successeur au cyclomoteur 103.",
    categories: ["economie"],
  },
  {
    date: "2025-10-27", displayDate: "27 octobre 2025",
    title: "Rénovation du local de l'épicerie solidaire",
    url: "https://www.estrepublicain.fr/societe/2025/10/27/renovation-du-local-de-l-epicerie-solidaire",
    source: "Est Républicain",
    summary: "L'épicerie solidaire de Mandeure et Mathay a fait peau neuve grâce à une rénovation de son local incluant un nouveau sol.",
    categories: ["securite"],
  },
  {
    date: "2025-10-23", displayDate: "23 octobre 2025",
    title: "Soirée théâtrale « Coup de bluff au cabaret »",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/10/23/soiree-theatrale-coup-de-bluff-au-cabaret",
    source: "Est Républicain",
    summary: "Le centre culturel Jean-d'Ormesson de Mandeure accueille la comédie « Coup de bluff au cabaret » un vendredi soir.",
    categories: ["culture"],
  },
  {
    date: "2025-10-22", displayDate: "22 octobre 2025",
    title: "Plus de 1 300 € récoltés au bénéfice de la lutte contre le cancer du sein",
    url: "https://www.estrepublicain.fr/sante/2025/10/22/plus-de-1-300-recoltes-au-benefice-de-la-lutte-contre-le-cancer-du-sein",
    source: "Est Républicain",
    summary: "La Ville de Mandeure et son CCAS ont organisé les animations d'Octobre rose le 16 octobre, permettant de récolter plus de 1 300 euros pour la lutte contre le cancer du sein.",
    categories: ["securite"],
  },
  {
    date: "2025-10-15", displayDate: "15 octobre 2025",
    title: "Deux dispositifs innovants pour lutter contre le décrochage scolaire",
    url: "https://www.estrepublicain.fr/education/2025/10/15/deux-dispositifs-innovants-pour-lutter-contre-le-decrochage-scolaire",
    source: "Est Républicain",
    summary: "La Maison familiale et rurale de Mandeure s'engage dans deux dispositifs destinés à prévenir le décrochage scolaire et à améliorer le bien-être des élèves.",
    categories: ["culture"],
  },
  {
    date: "2025-10-10", displayDate: "10 octobre 2025",
    title: "L'association Mémoire et souvenir dresse le bilan annuel",
    url: "https://www.estrepublicain.fr/societe/2025/10/10/l-association-memoire-et-souvenir-dresse-le-bilan-annuel",
    source: "Est Républicain",
    summary: "L'association Mémoire et souvenir de la résistance du Pays de Montbéliard, basée à Mandeure, a tenu son assemblée générale 2025 et dressé son bilan annuel.",
    categories: ["culture"],
  },
  {
    date: "2025-10-09", displayDate: "9 octobre 2025",
    title: "Marche aux lampions pour Octobre Rose, jeudi 16 octobre",
    url: "https://www.estrepublicain.fr/sante/2025/10/09/marche-aux-lampions-pour-octobre-rose-jeudi-16-octobre",
    source: "Est Républicain",
    summary: "Le CCAS de Mandeure organise une marche aux lampions dans le cadre d'Octobre Rose.",
    categories: ["securite"],
  },
  {
    date: "2025-09-28", displayDate: "28 septembre 2025",
    title: "La chorale « Couleurs vocales » ouvre prochainement ses portes aux nouveaux talents",
    url: "https://www.estrepublicain.fr/societe/2025/09/28/la-chorale-couleurs-vocales-ouvre-prochainement-ses-portes-aux-nouveaux-talents",
    source: "Est Républicain",
    summary: "La chorale Couleurs vocales, qui répète au Majestic à Mandeure depuis le 8 septembre, s'ouvre à de nouveaux choristes.",
    categories: ["culture"],
  },
  {
    date: "2025-09-26", displayDate: "26 septembre 2025",
    title: "Spéléologie : à la découverte du patrimoine souterrain",
    url: "https://www.estrepublicain.fr/societe/2025/09/26/speleologie-a-la-decouverte-du-patrimoine-souterrain",
    source: "Est Républicain",
    summary: "Le Groupe spéléo-archéo de Mandeure organise les Journées nationales de spéléologie, avec une visite d'une rivière souterraine.",
    categories: ["culture"],
  },
  {
    date: "2025-09-24", displayDate: "24 septembre 2025",
    title: "Découvrir le monde souterrain avec des spéléologues",
    url: "https://www.estrepublicain.fr/environnement/2025/09/24/decouvrir-le-monde-souterrain-avec-des-speleologues",
    source: "Est Républicain",
    summary: "À l'occasion des Journées nationales de la spéléologie, le Groupe Spéléo Archéo de Mandeure (GSAM) propose une visite de la rivière souterraine de la commune voisine de Rang.",
    categories: ["culture"],
  },
  {
    date: "2025-09-20", displayDate: "20 septembre 2025",
    title: "Marche populaire le dimanche 5 octobre",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/09/20/marche-populaire-le-dimanche-5-octobre",
    source: "Est Républicain",
    summary: "Les amateurs de randonnée sont invités à participer à une marche populaire organisée à Mandeure.",
    categories: ["sport"],
  },
  {
    date: "2025-09-20", displayDate: "20 septembre 2025",
    title: "Quelques incontournables des Journées européennes du patrimoine",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/09/20/quelques-incontournables-des-journees-europeennes-du-patrimoine",
    source: "Est Républicain",
    summary: "Parmi les sites à découvrir lors des Journées européennes du patrimoine, le théâtre gallo-romain de Mandeure s'anime avec une reconstitution proposée par la troupe des Trimatrici.",
    categories: ["culture"],
  },
  {
    date: "2025-09-11", displayDate: "11 septembre 2025",
    title: "Victoire du maquis du Lomont : 81 ans de mémoire et courage",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/09/11/victoire-du-maquis-du-lomont-81-ans-de-memoire-et-courage",
    source: "Est Républicain",
    summary: "La commune de Mandeure a organisé une cérémonie commémorative en mémoire des maquisards du Lomont, à l'occasion du 81e anniversaire de leur victoire.",
    categories: ["culture"],
  },
  {
    date: "2025-09-07", displayDate: "7 septembre 2025",
    title: "La journée parfaite de Benjamin Mocco (CC Pays de Vesoul HS)",
    url: "https://www.estrepublicain.fr/sport/2025/09/07/la-journee-parfaite-de-benjamin-mocco-(cc-pays-de-vesoul-hs)",
    source: "Est Républicain",
    summary: "La piste du Belvédère à Mandeure, gérée par le club AV Beaulieu Mandeure, a accueilli la rentrée BMX régionale, marquée par la performance du coureur vésulien Benjamin Mocco.",
    categories: ["sport"],
  },
  {
    date: "2025-09-05", displayDate: "5 septembre 2025",
    title: "La Coupe Bourgogne Franche-Comté commence à Mandeure",
    url: "https://www.estrepublicain.fr/sport/2025/09/05/la-coupe-bourgogne-franche-comte-commence-a-mandeure",
    source: "Est Républicain",
    summary: "La première manche de la Coupe Bourgogne Franche-Comté de BMX s'est disputée à Mandeure.",
    categories: ["sport"],
  },
  {
    date: "2025-09-01", displayDate: "1 septembre 2025",
    title: "Nouveaux visages à la rentrée du collège Jean-Paul Guyot",
    url: "https://www.estrepublicain.fr/education/2025/09/01/nouveaux-visages-a-la-rentree-du-college-jean-paul-guyot",
    source: "Est Républicain",
    summary: "Le collège Jean-Paul Guyot de Mandeure a fait sa rentrée dans une atmosphère sereine, prêt à accueillir environ 310 élèves.",
    categories: ["culture"],
  },
  {
    date: "2025-09-01", displayDate: "1 septembre 2025",
    title: "Visite guidée des fours à chaux ce dimanche 7 septembre",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/09/01/visite-guidee-des-fours-a-chaux-ce-dimanche-7-septembre",
    source: "Est Républicain",
    summary: "Une visite guidée sur le site du théâtre antique de Mandeure permet de découvrir les vestiges des anciens fours à chaux des environs.",
    categories: ["culture"],
  },
  {
    date: "2025-08-31", displayDate: "31 août 2025",
    title: "Une nouvelle directrice à la maternelle Frédéric-Bataille",
    url: "https://www.estrepublicain.fr/education/2025/08/31/une-nouvelle-directrice-a-la-maternelle-frederic-bataille",
    source: "Est Républicain",
    summary: "Manon Grasset, arrivée de Reims, devient la nouvelle directrice de l'école maternelle Frédéric-Bataille de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2025-08-30", displayDate: "30 août 2025",
    title: "Le forum annuel de l'ASCBM, ce samedi pour favoriser les inscriptions",
    url: "https://www.estrepublicain.fr/societe/2025/08/30/le-forum-annuel-de-l-ascbm-ce-samedi-pour-favoriser-les-inscriptions",
    source: "Est Républicain",
    summary: "L'Association socioculturelle de Mandeure (ASCBM) organise son forum annuel des associations pour encourager les inscriptions.",
    categories: ["culture"],
  },
  {
    date: "2025-08-28", displayDate: "28 août 2025",
    title: "Dégustations et animations au marché du soir, ce vendredi 29 août",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/08/28/degustations-et-animations-au-marche-du-soir-ce-vendredi-29-aout",
    source: "Est Républicain",
    summary: "Le marché du soir organisé par Pays de Montbéliard Agglomération se tient à Mandeure avec dégustations et animations.",
    categories: ["economie", "culture"],
  },
  {
    date: "2025-08-26", displayDate: "26 août 2025",
    title: "Visite guidée du théâtre d'Epomanduodurum",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/08/26/visite-guidee-du-theatre-d-epomanduodurum",
    source: "Est Républicain",
    summary: "Une visite guidée permet de découvrir le théâtre antique de l'agglomération gallo-romaine d'Epomanduodurum, ancien nom de Mandeure.",
    categories: ["culture"],
  },
  {
    date: "2025-08-25", displayDate: "25 août 2025",
    title: "Rentrée échelonnée au collège Jean-Paul Guyot",
    url: "https://www.estrepublicain.fr/education/2025/08/25/rentree-echelonnee-au-college-jean-paul-guyot",
    source: "Est Républicain",
    summary: "Comme chaque année, la rentrée au collège Jean-Paul Guyot à Mandeure se fait de façon échelonnée selon les niveaux.",
    categories: ["culture"],
  },
  {
    date: "2025-08-24", displayDate: "24 août 2025",
    title: "Un marché du soir vendredi 29 août avec plus de 40 producteurs locaux",
    url: "https://www.estrepublicain.fr/culture-loisirs/2025/08/24/un-marche-du-soir-vendredi-29-aout-avec-plus-de-40-producteurs-locaux",
    source: "Est Républicain",
    summary: "Un marché du soir réunissant plus de 40 producteurs locaux se tient au centre culturel Jean d'Ormesson de Mandeure.",
    categories: ["economie", "culture"],
  },
  {
    date: "2025-08-24", displayDate: "24 août 2025",
    title: "« Duo en sur régime » : un pari fou de Mandeure à Oleiros (Portugal)",
    url: "https://www.estrepublicain.fr/insolite/2025/08/24/duo-en-sur-regime-un-pari-fou-de-mandeure-a-oleiros-(portugal)",
    source: "Est Républicain",
    summary: "Le mécanicien Émilien Huot et l'amateur de défis Loïc Valker, tous deux de Mandeure, ont parcouru plus de 1 900 km en quatre jours dans le cadre d'un pari original.",
    categories: ["culture"],
  },
];
